// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"overflow-hidden bg-gray-50 px-8 sm:grid sm:grid-cols-2 sm:items-center dark:bg-gray-900\"><div class=\"max-w-full md:p-12 lg:px-16 lg:py-24\"><div class=\"max-w-full text-center\"><p class=\"hidden p-8 text-gray-500 md:mt-4 my-4 md:block dark:text-gray-400\">WoW-Tracker aims to keep track of numerous stats and other interesting stuff about your WoW-characters. To get started tracking stuff import your character below!</p><div class=\"mt-4 mb-8 md:mt-8 md:mb-8 flex justify-center justify-items-center\" id=\"import-container\"><a class=\"btn btn-accent btn-soft\" hx-get=\"/import-home\" hx-swap=\"innerHTML\" hx-target=\"#import-container\">Import new character</a></div></div></div><img alt=\"\" src=\"/static/img/splash.png\" class=\"w-full object-cover sm:h-[calc(100%_-_2rem)] sm:self-end sm:rounded-ss-[30px] md:h-[calc(100%_-_4rem)] md:rounded-ss-[60px]\" style=\"width: 80%;\"></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
